### ISSUE TITLE
Redis does not start on freebsd

### ISSUE THREAD

**Issue by shortdudey123** [sous-chefs/redisio#327]
Kitchen verify fails since redis does not start

Kitchen logs show it does though
```
 * service[redis6379] action start[2017-04-27T06:44:37+00:00] INFO: Processing service[redis6379] action start (redisio::configure line 66)
[2017-04-27T06:44:37+00:00] DEBUG: service[redis6379] found at /usr/local/etc/rc.d/redis6379
[2017-04-27T06:44:37+00:00] DEBUG: service[redis6379] supports status, running
Cannot 'status' redis6379. Set redis6379_enable to YES in /etc/rc.conf or use 'onestatus' instead of 'status'.
[2017-04-27T06:44:37+00:00] DEBUG: service[redis6379] is running
[2017-04-27T06:44:37+00:00] DEBUG: redis6379 enable/disable state unknown
[2017-04-27T06:44:37+00:00] DEBUG: service[redis6379] already running - nothing to do
(up to date)
```

Logging into the kitchen instance, calling `service redis6379 start`, then running verify again works.

**Comment by shortdudey123** [comment]
Don't think this is related, but there is warnings after the converge finishes
```
Apr 27 06:44:36 freebsd-10 pkg: redis-3.2.8 installed
Apr 27 06:44:52 freebsd-10 vagrant: /usr/sbin/service: WARNING: $growfs_enable is not set properly - see rc.conf(5).
Apr 27 06:44:52 freebsd-10 vagrant: /usr/sbin/service: WARNING: $ is not set properly - see rc.conf(5).
Apr 27 06:44:52 freebsd-10 vagrant: /usr/sbin/service: WARNING: $sentinel_enable is not set properly - see rc.conf(5).
Apr 27 06:44:52 freebsd-10 vagrant: /usr/sbin/service: WARNING: $redis_enable is not set properly - see rc.conf(5).
Apr 27 06:44:52 freebsd-10 vagrant: /usr/sbin/service: WARNING: $dbus_enable is not set properly - see rc.conf(5).
```

**Comment by shortdudey123** [comment]
Full output from the verify stage
```
-----> Verifying <default-freebsd-103-121936>...
       Preparing files for transfer
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
       Successfully installed thor-0.19.0
Fetching: busser-0.7.1.gem (100%)
       Successfully installed busser-0.7.1
       2 gems installed
       Installing Busser plugins: busser-serverspec
       Plugin serverspec installed (version 0.5.10)
-----> Running postinstall for serverspec plugin
       Suite path directory /tmp/verifier/suites does not exist, skipping.
       Transferring files to <default-freebsd-103-121936>
-----> Running serverspec test suite
-----> Installing Serverspec..
Fetching: diff-lcs-1.3.gem (100%)
Fetching: rspec-expectations-3.5.0.gem (100%)
Fetching: rspec-mocks-3.5.0.gem (100%)
Fetching: rspec-3.5.0.gem (100%)
Fetching: rspec-its-1.2.0.gem (100%)
Fetching: multi_json-1.12.1.gem (100%)
Fetching: net-ssh-4.1.0.gem (100%)
Fetching: net-scp-1.2.1.gem (100%)
Fetching: net-telnet-0.1.1.gem (100%)
Fetching: sfl-2.3.gem (100%)
Fetching: specinfra-2.67.9.gem (100%)
Fetching: serverspec-2.38.0.gem (100%)
-----> serverspec installed (version 2.38.0)
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.5.0/lib:/tmp/verifier/gems/gems/rspec-core-3.5.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec
       
       Redis
         behaves like redis on port
       WARNING: ignoring the provided expectation message argument ({:if=>true}) since it is not a string or a proc.
           enables the redis service (FAILED - 1)
           is listening on port 6379 (FAILED - 2)
       
       File "/usr/local/etc/redis/savetest.conf"
         should be file
         content
           should match "save a"
         content
           should match "save b"
         content
           should match "save c"
       
       Failures:
       
         1) Redis behaves like redis on port enables the redis service
            Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
              {:if=>true}
              /bin/sh -c ps\ aux\ \|\ grep\ -w\ --\ redis6379\ \|\ grep\ -qv\ grep
              
            Shared Example Group: "redis on port" called from /tmp/verifier/suites/serverspec/redisio_spec.rb:4
            # /tmp/verifier/suites/serverspec/redisio_examples.rb:12:in `block (2 levels) in <top (required)>'
       
         2) Redis behaves like redis on port is listening on port 6379
            Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
              expected Port "6379" to be listening
              /bin/sh -c sockstat\ -46l\ -p\ 6379\ \|\ grep\ --\ :6379\\\ 
              
            Shared Example Group: "redis on port" called from /tmp/verifier/suites/serverspec/redisio_spec.rb:4
            # /tmp/verifier/suites/serverspec/redisio_examples.rb:22:in `block (2 levels) in <top (required)>'
       
       Finished in 0.61231 seconds (files took 0.83727 seconds to load)
       6 examples, 2 failures
       
       Failed examples:
       
       rspec '/tmp/verifier/suites/serverspec/redisio_spec.rb[1:1:1]' # Redis behaves like redis on port enables the redis service
       rspec '/tmp/verifier/suites/serverspec/redisio_spec.rb[1:1:3]' # Redis behaves like redis on port is listening on port 6379
       
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.5.0/lib:/tmp/verifier/gems/gems/rspec-core-3.5.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec failed
       !!!!!! Ruby Script [/tmp/verifier/gems/gems/busser-serverspec-0.5.10/lib/busser/runner_plugin/../serverspec/runner.rb /tmp/verifier/suites/serverspec] exit code was 1
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <default-freebsd-103-121936>.  Please see .kitchen/logs/default-freebsd-103-121936.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Logging into the instance shows that verify is correct
```
$ service redis6379 status
redis6379 is not running.
$ 
$ ps aux | grep redis
vagrant 1652   0.0  0.2 18832 2228  0  S+    7:04PM 0:00.00 grep redis
$ 
```

**Comment by shortdudey123** [comment]
Starting the service manually on the kitchen instance then running verify again works
```
$ sudo service redis6379 start
Starting redis6379.
$ 
```
```
-----> Verifying <default-freebsd-103-121936>...
       Preparing files for transfer
-----> Busser installation detected (busser)
       Installing Busser plugins: busser-serverspec
       Plugin serverspec already installed
       Removing /tmp/verifier/suites/serverspec
       Transferring files to <default-freebsd-103-121936>
-----> Running serverspec test suite
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.5.0/lib:/tmp/verifier/gems/gems/rspec-core-3.5.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec
       
       Redis
         behaves like redis on port
       WARNING: ignoring the provided expectation message argument ({:if=>true}) since it is not a string or a proc.
           enables the redis service
           is listening on port 6379
       
       File "/usr/local/etc/redis/savetest.conf"
         should be file
         content
           should match "save a"
         content
           should match "save b"
         content
           should match "save c"
       
       Finished in 0.55816 seconds (files took 0.60089 seconds to load)
       6 examples, 0 failures
       
       Finished verifying <default-freebsd-103-121936> (0m3.25s).
-----> Kitchen is finished. (0m4.20s)
```

**Comment by shortdudey123** [comment]
Content of the rc.d service file
```
$ cat /usr/local/etc/rc.d/redis6379
#!/bin/sh
#
#

# PROVIDE: redis6379
# REQUIRE: LOGIN
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `redis':
#
#redis6379_enable="YES"
#
# Define profiles here to run separate redis instances:
#
#redis_profiles="foo bar" #  Script uses /usr/local/etc/redis-NAME.conf respectively.
#                            For correct script working please update pidfile entries in
#                            redis-NAME.conf files.

. /etc/rc.subr

name="redis6379"
rcvar="${name}_enable"

extra_commands="reload"

command="/usr/local/bin/redis-server"
pidfile="/var/run/redis/6379/redis_6379.pid"

# read configuration and set defaults
load_rc_config "$name"
: ${redis6379_enable="NO"}
: ${redis_user="redis"}
: ${redis_config="/usr/local/etc/redis/6379.conf"}

command_args="${redis_config}"
required_files="${redis_config}"

_profile_exists() {
        for _p in ${redis_profiles}; do
                [ "${_p}" = "$1" ] && return 1;
        done
        return 0
}

if [ $# -eq 2 ]; then
        _profile=$2
        _profile_exists $_profile
        _exists=$?
        [ ${_exists} -ne 1 ] && {
                echo "`basename /usr/local/etc/rc.d/redis`: no '$2' in 'redis_profiles'"
                exit 1
        };
        echo "-- Profile: ${name} --"
        config_file="/usr/local/etc/redis/${name}.conf"
        command_args="${config_file}"
        pidfile="/var/run/redis/6379/${name}.pid"
        required_files="${config_file}"
elif [ -n "${redis_profiles}" ]; then
        _swap=$*; shift; _profiles=$*
        _profiles=${_profiles:-${redis_profiles}}
        set -- ${_swap}
        for _profile in ${_profiles}; do
                /usr/local/etc/rc.d/redis $1 ${_profile}
        done
        exit 0
fi

run_rc_command "$1"$ 
```
```
$ cat /etc/rc.conf
zfs_enable="YES"
hostname="default-freebsd-103-121936.vagrantup.com"
ifconfig_em0="dhcp"
sshd_enable="YES"
rpcbind_enable="YES"
nfs_server_enable="YES"
mountd_flags="-r"
vboxnet_enable="YES"
vboxguest_enable="YES"
vboxservice_enable="YES"
ifconfig_vtnet0_name="em0"
ifconfig_vtnet1_name="em1"
ifconfig_vtnet2_name="em2"
ifconfig_vtnet3_name="em3"
redis6379_enable="YES"
redissavetest_enable="YES"
$ 
```

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
