### ISSUE TITLE
uninitialized constant Chef::Resource::RedisioInstall

### ISSUE THREAD

**Issue by cody-adams** [sous-chefs/redisio#353]
I'm getting this error when I run redisio::default recipe with Chef 13

` ================================================================================  Error executing action run on resource 'redisio_install[redis-installation]' ================================================================================
    
    NameError
    ---------
    uninitialized constant Chef::Resource::RedisioInstall
    Did you mean?  RedisioHelper
    
    Cookbook Trace:
    ---------------
    /opt/kitchen/cache/cookbooks/redisio/providers/install.rb:109:in `load_current_resource'
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/redisio/recipes/install.rb
    
     32:   redisio_install 'redis-installation' do
     33:     version redis['version'] if redis['version']
     34:     download_url location
     35:     safe_install redis['safe_install']
     36:     install_dir redis['install_dir'] if redis['install_dir']
     37:   end
     38: end
     39: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/redisio/recipes/install.rb:32:in `from_file'
    
    redisio_install("redis-installation") do
      action [:run]
      default_guard_interpreter :default
      declared_type :redisio_install
      cookbook_name "redisio"
      recipe_name "install"
      version "2.8.10"
      download_url "http://download.redis.io/releases//redis-2.8.10.tar.gz"
      safe_install true
      install_dir "/opt"
    end
    
    System Info:
    ------------
    chef_version=13.0.118
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=1954;start=19:50:12;
    executable=/opt/chef/embedded/bin/chef-client`

Here is the recipe I am using along with the attributes

` 
node.default['redisio']['default_settings']['syslogenabled'] = false
node.default['redisio']['default_settings']['logfile'] = '/var/log/redis.log'
node.default['redisio']['servers'] = [
  {
    'name' => '-results-backend',
    'port' => '6379',
    'data_bag_name' => '***',
    'data_bag_item' => '***',
    'data_bag_key' => '***'
  }
]

include_recipe 'apt'
include_recipe 'build-essential'
include_recipe 'redisio'
include_recipe 'redisio::enable'`

This works fine in Chef 11 and 12
Any help in debugging this would be appreciated.

**Comment by davidski** [comment]
This cookbook doesn't currently support Chef 13. See #319 for tracking and for a proposed PR that adds Chef 13 client support.

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
