### ISSUE TITLE
undefined method `selinux_policy_install'

### ISSUE THREAD

**Issue by ariva07** [sous-chefs/redisio#393]
### Scenario:
Configure Redis on system with Selinux enabled gives error:
ERROR: redisio_configure[redis-servers] (redisio::configure line 34) had an error: NoMethodError: undefined method `selinux_policy_install'

### Steps to Reproduce:
use redisio::configure recipe to reproduce the problem

### Expected Result:
redisio::configure runs using apropriate dependencies or simply skip selinux_policy_install method so it could be launched outside the redisio cookbook

### Actual Result:
```Recipe:

 redisio::install
  * yum_package[redisio_package_name] action install (up to date)
Recipe: redisio::configure
  * redisio_configure[redis-servers] action run
    
    ================================================================================
    Error executing action `run` on resource 'redisio_configure[redis-servers]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `selinux_policy_install' for #<#<Class:0x000000000401a848>:0x0000000005a14348>
    
    Cookbook Trace:
    ---------------
    /chef/local-mode-cache/cache/cookbooks/redisio/providers/configure.rb:156:in `block (2 levels) in configure'
    /chef/local-mode-cache/cache/cookbooks/redisio/providers/configure.rb:95:in `block in configure'
    /chef/local-mode-cache/cache/cookbooks/redisio/providers/configure.rb:40:in `each'
    /chef/local-mode-cache/cache/cookbooks/redisio/providers/configure.rb:40:in `configure'
    /chef/local-mode-cache/cache/cookbooks/redisio/providers/configure.rb:22:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /chef/local-mode-cache/cache/cookbooks/redisio/recipes/configure.rb
    
     34: redisio_configure 'redis-servers' do
     35:   version redis['version'] if redis['version']
     36:   default_settings redis['default_settings']
     37:   servers redis_instances
     38:   base_piddir redis['base_piddir']
     39: end
     40: 
    
    Compiled Resource:
    ------------------
    # Declared in /chef/local-mode-cache/cache/cookbooks/redisio/recipes/configure.rb:34:in `from_file'
    
    redisio_configure("redis-servers") do
      action [:run]
      default_guard_interpreter :default
      declared_type :redisio_configure
      cookbook_name "redisio"
      recipe_name "configure"
      version "3.2.12-2.el7"
      default_settings {"user"=>"redis", "group"=>"redis", "homedir"=>"/var/lib/redis", "shell"=>"/bin/sh", "systemuser"=>true, "uid"=>nil, "ulimit"=>0, "configdir"=>"/etc/redis", "name"=>nil, "tcpbacklog"=>"511", "address"=>nil, "databases"=>"16", "backuptype"=>"rdb", "datadir"=>"/var/lib/redis", "unixsocket"=>nil, "unixsocketperm"=>nil, "timeout"=>"0", "keepalive"=>"0", "loglevel"=>"notice", "logfile"=>nil, "syslogenabled"=>"yes", "syslogfacility"=>"local0", "shutdown_save"=>false, "save"=>nil, "stopwritesonbgsaveerror"=>"yes", "rdbcompression"=>"yes", "rdbchecksum"=>"yes", "dbfilename"=>nil, "slaveof"=>nil, "protected_mode"=>nil, "masterauth"=>nil, "slaveservestaledata"=>"yes", "slavereadonly"=>"yes", "repldisklesssync"=>"no", "repldisklesssyncdelay"=>"5", "replpingslaveperiod"=>"10", "repltimeout"=>"60", "repldisabletcpnodelay"=>"no", "replbacklogsize"=>"1mb", "replbacklogttl"=>3600, "slavepriority"=>"100", "requirepass"=>nil, "rename_commands"=>nil, "maxclients"=>10000, "maxmemory"=>nil, "maxmemorypolicy"=>nil, "maxmemorysamples"=>nil, "appendfilename"=>nil, "appendfsync"=>"everysec", "noappendfsynconrewrite"=>"no", "aofrewritepercentage"=>"100", "aofrewriteminsize"=>"64mb", "aofloadtruncated"=>"yes", "luatimelimit"=>"5000", "slowloglogslowerthan"=>"10000", "slowlogmaxlen"=>"1024", "notifykeyspaceevents"=>"", "hashmaxziplistentries"=>"512", "hashmaxziplistvalue"=>"64", "listmaxziplistentries"=>"512", "listmaxziplistvalue"=>"64", "setmaxintsetentries"=>"512", "zsetmaxziplistentries"=>"128", "zsetmaxziplistvalue"=>"64", "hllsparsemaxbytes"=>"3000", "activerehasing"=>"yes", "clientoutputbufferlimit"=>[["normal", "0", "0", "0"], ["slave", "256mb", "64mb", "60"], ["pubsub", "32mb", "8mb", "60"]], "hz"=>"10", "aofrewriteincrementalfsync"=>"yes", "clusterenabled"=>"no", "clusterconfigfile"=>nil, "clusternodetimeout"=>5000, "includes"=>nil, "data_bag_name"=>nil, "data_bag_item"=>nil, "data_bag_key"=>nil, "minslavestowrite"=>nil, "minslavesmaxlag"=>nil, "breadcrumb"=>true}
      servers [{"port"=>"6379", "address"=>["x.y.a.a", "x.y.b.a", "x.y.c.a"], "clusterenabled"=>"yes"}, {"port"=>6380, "address"=>["x.y.a.a", "x.y.b.a", "x.y.c.a"], "clusterenabled"=>"yes"}]
      base_piddir "/var/run/redis"
    end
    
    System Info:
    ------------
    chef_version=13.4.24
    platform=centos
    platform_version=7.6.1810
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    program_name=chef-client worker: ppid=19468;start=08:10:13;
    executable=/opt/chef/bin/chef-client
    

Running handlers:
[2019-03-20T08:10:27+01:00] ERROR: Running exception handlers
Running handlers complete
[2019-03-20T08:10:27+01:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 14 seconds
[2019-03-20T08:10:28+01:00] FATAL: Stacktrace dumped to /chef/local-mode-cache/cache/chef-stacktrace.out
[2019-03-20T08:10:28+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-03-20T08:10:28+01:00] ERROR: redisio_configure[redis-servers] (redisio::configure line 34) had an error: NoMethodError: undefined method `selinux_policy_install' for #<#<Class:0x000000000401a848>:0x0000000005a14348>
[2019-03-20T08:10:28+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by devsibwarra** [comment]
What version of the `selinux_policy` cookbook do you have installed?  Looks like `selinux_policy_install` was added in [selinux_policy v2.2.0](https://github.com/sous-chefs/selinux_policy/compare/v2.1.0...v2.2.0), so that might need to become a min requirement in the redisio metadata
